// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/payment.proto

package paymentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardInformation struct {
	CardNumber           string   `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Cvv                  string   `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardInformation) Reset()         { *m = CardInformation{} }
func (m *CardInformation) String() string { return proto.CompactTextString(m) }
func (*CardInformation) ProtoMessage()    {}
func (*CardInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{0}
}

func (m *CardInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardInformation.Unmarshal(m, b)
}
func (m *CardInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardInformation.Marshal(b, m, deterministic)
}
func (m *CardInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardInformation.Merge(m, src)
}
func (m *CardInformation) XXX_Size() int {
	return xxx_messageInfo_CardInformation.Size(m)
}
func (m *CardInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_CardInformation.DiscardUnknown(m)
}

var xxx_messageInfo_CardInformation proto.InternalMessageInfo

func (m *CardInformation) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *CardInformation) GetCvv() string {
	if m != nil {
		return m.Cvv
	}
	return ""
}

func (m *CardInformation) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

type RegistCardRequest struct {
	CardInformation      *CardInformation `protobuf:"bytes,1,opt,name=card_information,json=cardInformation,proto3" json:"card_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegistCardRequest) Reset()         { *m = RegistCardRequest{} }
func (m *RegistCardRequest) String() string { return proto.CompactTextString(m) }
func (*RegistCardRequest) ProtoMessage()    {}
func (*RegistCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{1}
}

func (m *RegistCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistCardRequest.Unmarshal(m, b)
}
func (m *RegistCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistCardRequest.Marshal(b, m, deterministic)
}
func (m *RegistCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistCardRequest.Merge(m, src)
}
func (m *RegistCardRequest) XXX_Size() int {
	return xxx_messageInfo_RegistCardRequest.Size(m)
}
func (m *RegistCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistCardRequest proto.InternalMessageInfo

func (m *RegistCardRequest) GetCardInformation() *CardInformation {
	if m != nil {
		return m.CardInformation
	}
	return nil
}

type RegistCardResponse struct {
	CardToken            string   `protobuf:"bytes,1,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	IsOk                 bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistCardResponse) Reset()         { *m = RegistCardResponse{} }
func (m *RegistCardResponse) String() string { return proto.CompactTextString(m) }
func (*RegistCardResponse) ProtoMessage()    {}
func (*RegistCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{2}
}

func (m *RegistCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistCardResponse.Unmarshal(m, b)
}
func (m *RegistCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistCardResponse.Marshal(b, m, deterministic)
}
func (m *RegistCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistCardResponse.Merge(m, src)
}
func (m *RegistCardResponse) XXX_Size() int {
	return xxx_messageInfo_RegistCardResponse.Size(m)
}
func (m *RegistCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistCardResponse proto.InternalMessageInfo

func (m *RegistCardResponse) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *RegistCardResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type PaymentInformation struct {
	CardToken            string               `protobuf:"bytes,1,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	ReservationId        int32                `protobuf:"varint,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Datetime             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Amount               int32                `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IsCanceled           bool                 `protobuf:"varint,5,opt,name=is_canceled,json=isCanceled,proto3" json:"is_canceled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentInformation) Reset()         { *m = PaymentInformation{} }
func (m *PaymentInformation) String() string { return proto.CompactTextString(m) }
func (*PaymentInformation) ProtoMessage()    {}
func (*PaymentInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{3}
}

func (m *PaymentInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInformation.Unmarshal(m, b)
}
func (m *PaymentInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInformation.Marshal(b, m, deterministic)
}
func (m *PaymentInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInformation.Merge(m, src)
}
func (m *PaymentInformation) XXX_Size() int {
	return xxx_messageInfo_PaymentInformation.Size(m)
}
func (m *PaymentInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInformation proto.InternalMessageInfo

func (m *PaymentInformation) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *PaymentInformation) GetReservationId() int32 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *PaymentInformation) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *PaymentInformation) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentInformation) GetIsCanceled() bool {
	if m != nil {
		return m.IsCanceled
	}
	return false
}

type ExecutePaymentRequest struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ExecutePaymentRequest) Reset()         { *m = ExecutePaymentRequest{} }
func (m *ExecutePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentRequest) ProtoMessage()    {}
func (*ExecutePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{4}
}

func (m *ExecutePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentRequest.Unmarshal(m, b)
}
func (m *ExecutePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentRequest.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentRequest.Merge(m, src)
}
func (m *ExecutePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentRequest.Size(m)
}
func (m *ExecutePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentRequest proto.InternalMessageInfo

func (m *ExecutePaymentRequest) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

type ExecutePaymentResponse struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	IsOk                 bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutePaymentResponse) Reset()         { *m = ExecutePaymentResponse{} }
func (m *ExecutePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentResponse) ProtoMessage()    {}
func (*ExecutePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{5}
}

func (m *ExecutePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentResponse.Unmarshal(m, b)
}
func (m *ExecutePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentResponse.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentResponse.Merge(m, src)
}
func (m *ExecutePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentResponse.Size(m)
}
func (m *ExecutePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentResponse proto.InternalMessageInfo

func (m *ExecutePaymentResponse) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *ExecutePaymentResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type CancelPaymentRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentRequest) Reset()         { *m = CancelPaymentRequest{} }
func (m *CancelPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentRequest) ProtoMessage()    {}
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{6}
}

func (m *CancelPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentRequest.Unmarshal(m, b)
}
func (m *CancelPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentRequest.Marshal(b, m, deterministic)
}
func (m *CancelPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentRequest.Merge(m, src)
}
func (m *CancelPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentRequest.Size(m)
}
func (m *CancelPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentRequest proto.InternalMessageInfo

func (m *CancelPaymentRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type CancelPaymentResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentResponse) Reset()         { *m = CancelPaymentResponse{} }
func (m *CancelPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentResponse) ProtoMessage()    {}
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{7}
}

func (m *CancelPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentResponse.Unmarshal(m, b)
}
func (m *CancelPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentResponse.Marshal(b, m, deterministic)
}
func (m *CancelPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentResponse.Merge(m, src)
}
func (m *CancelPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentResponse.Size(m)
}
func (m *CancelPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentResponse proto.InternalMessageInfo

func (m *CancelPaymentResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type BulkCancelPaymentRequest struct {
	PaymentId            []string `protobuf:"bytes,1,rep,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkCancelPaymentRequest) Reset()         { *m = BulkCancelPaymentRequest{} }
func (m *BulkCancelPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*BulkCancelPaymentRequest) ProtoMessage()    {}
func (*BulkCancelPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{8}
}

func (m *BulkCancelPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkCancelPaymentRequest.Unmarshal(m, b)
}
func (m *BulkCancelPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkCancelPaymentRequest.Marshal(b, m, deterministic)
}
func (m *BulkCancelPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkCancelPaymentRequest.Merge(m, src)
}
func (m *BulkCancelPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_BulkCancelPaymentRequest.Size(m)
}
func (m *BulkCancelPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkCancelPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkCancelPaymentRequest proto.InternalMessageInfo

func (m *BulkCancelPaymentRequest) GetPaymentId() []string {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

type BulkCancelPaymentResponse struct {
	Deleted              int32    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkCancelPaymentResponse) Reset()         { *m = BulkCancelPaymentResponse{} }
func (m *BulkCancelPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*BulkCancelPaymentResponse) ProtoMessage()    {}
func (*BulkCancelPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{9}
}

func (m *BulkCancelPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkCancelPaymentResponse.Unmarshal(m, b)
}
func (m *BulkCancelPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkCancelPaymentResponse.Marshal(b, m, deterministic)
}
func (m *BulkCancelPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkCancelPaymentResponse.Merge(m, src)
}
func (m *BulkCancelPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_BulkCancelPaymentResponse.Size(m)
}
func (m *BulkCancelPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkCancelPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkCancelPaymentResponse proto.InternalMessageInfo

func (m *BulkCancelPaymentResponse) GetDeleted() int32 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type GetPaymentInformationRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentInformationRequest) Reset()         { *m = GetPaymentInformationRequest{} }
func (m *GetPaymentInformationRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationRequest) ProtoMessage()    {}
func (*GetPaymentInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{10}
}

func (m *GetPaymentInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationRequest.Unmarshal(m, b)
}
func (m *GetPaymentInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationRequest.Merge(m, src)
}
func (m *GetPaymentInformationRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationRequest.Size(m)
}
func (m *GetPaymentInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationRequest proto.InternalMessageInfo

func (m *GetPaymentInformationRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type GetPaymentInformationResponse struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	IsOk                 bool                `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPaymentInformationResponse) Reset()         { *m = GetPaymentInformationResponse{} }
func (m *GetPaymentInformationResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationResponse) ProtoMessage()    {}
func (*GetPaymentInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{11}
}

func (m *GetPaymentInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationResponse.Unmarshal(m, b)
}
func (m *GetPaymentInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationResponse.Merge(m, src)
}
func (m *GetPaymentInformationResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationResponse.Size(m)
}
func (m *GetPaymentInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationResponse proto.InternalMessageInfo

func (m *GetPaymentInformationResponse) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func (m *GetPaymentInformationResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type InitializeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{12}
}

func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (m *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(m, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

type InitializeResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeResponse) Reset()         { *m = InitializeResponse{} }
func (m *InitializeResponse) String() string { return proto.CompactTextString(m) }
func (*InitializeResponse) ProtoMessage()    {}
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{13}
}

func (m *InitializeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeResponse.Unmarshal(m, b)
}
func (m *InitializeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeResponse.Marshal(b, m, deterministic)
}
func (m *InitializeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeResponse.Merge(m, src)
}
func (m *InitializeResponse) XXX_Size() int {
	return xxx_messageInfo_InitializeResponse.Size(m)
}
func (m *InitializeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeResponse proto.InternalMessageInfo

func (m *InitializeResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type GetResultRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultRequest) Reset()         { *m = GetResultRequest{} }
func (m *GetResultRequest) String() string { return proto.CompactTextString(m) }
func (*GetResultRequest) ProtoMessage()    {}
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{14}
}

func (m *GetResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultRequest.Unmarshal(m, b)
}
func (m *GetResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultRequest.Marshal(b, m, deterministic)
}
func (m *GetResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultRequest.Merge(m, src)
}
func (m *GetResultRequest) XXX_Size() int {
	return xxx_messageInfo_GetResultRequest.Size(m)
}
func (m *GetResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultRequest proto.InternalMessageInfo

type RawData struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	CardInformation      *CardInformation    `protobuf:"bytes,2,opt,name=card_information,json=cardInformation,proto3" json:"card_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RawData) Reset()         { *m = RawData{} }
func (m *RawData) String() string { return proto.CompactTextString(m) }
func (*RawData) ProtoMessage()    {}
func (*RawData) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{15}
}

func (m *RawData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawData.Unmarshal(m, b)
}
func (m *RawData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawData.Marshal(b, m, deterministic)
}
func (m *RawData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawData.Merge(m, src)
}
func (m *RawData) XXX_Size() int {
	return xxx_messageInfo_RawData.Size(m)
}
func (m *RawData) XXX_DiscardUnknown() {
	xxx_messageInfo_RawData.DiscardUnknown(m)
}

var xxx_messageInfo_RawData proto.InternalMessageInfo

func (m *RawData) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func (m *RawData) GetCardInformation() *CardInformation {
	if m != nil {
		return m.CardInformation
	}
	return nil
}

type GetResultResponse struct {
	RawData              []*RawData `protobuf:"bytes,1,rep,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	IsOk                 bool       `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResultResponse) Reset()         { *m = GetResultResponse{} }
func (m *GetResultResponse) String() string { return proto.CompactTextString(m) }
func (*GetResultResponse) ProtoMessage()    {}
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_595799929d632654, []int{16}
}

func (m *GetResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultResponse.Unmarshal(m, b)
}
func (m *GetResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultResponse.Marshal(b, m, deterministic)
}
func (m *GetResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultResponse.Merge(m, src)
}
func (m *GetResultResponse) XXX_Size() int {
	return xxx_messageInfo_GetResultResponse.Size(m)
}
func (m *GetResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultResponse proto.InternalMessageInfo

func (m *GetResultResponse) GetRawData() []*RawData {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *GetResultResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func init() {
	proto.RegisterType((*CardInformation)(nil), "paymentpb.CardInformation")
	proto.RegisterType((*RegistCardRequest)(nil), "paymentpb.RegistCardRequest")
	proto.RegisterType((*RegistCardResponse)(nil), "paymentpb.RegistCardResponse")
	proto.RegisterType((*PaymentInformation)(nil), "paymentpb.PaymentInformation")
	proto.RegisterType((*ExecutePaymentRequest)(nil), "paymentpb.ExecutePaymentRequest")
	proto.RegisterType((*ExecutePaymentResponse)(nil), "paymentpb.ExecutePaymentResponse")
	proto.RegisterType((*CancelPaymentRequest)(nil), "paymentpb.CancelPaymentRequest")
	proto.RegisterType((*CancelPaymentResponse)(nil), "paymentpb.CancelPaymentResponse")
	proto.RegisterType((*BulkCancelPaymentRequest)(nil), "paymentpb.BulkCancelPaymentRequest")
	proto.RegisterType((*BulkCancelPaymentResponse)(nil), "paymentpb.BulkCancelPaymentResponse")
	proto.RegisterType((*GetPaymentInformationRequest)(nil), "paymentpb.GetPaymentInformationRequest")
	proto.RegisterType((*GetPaymentInformationResponse)(nil), "paymentpb.GetPaymentInformationResponse")
	proto.RegisterType((*InitializeRequest)(nil), "paymentpb.InitializeRequest")
	proto.RegisterType((*InitializeResponse)(nil), "paymentpb.InitializeResponse")
	proto.RegisterType((*GetResultRequest)(nil), "paymentpb.GetResultRequest")
	proto.RegisterType((*RawData)(nil), "paymentpb.RawData")
	proto.RegisterType((*GetResultResponse)(nil), "paymentpb.GetResultResponse")
}

func init() { proto.RegisterFile("pb/payment.proto", fileDescriptor_595799929d632654) }

var fileDescriptor_595799929d632654 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x51, 0x6b, 0xd3, 0x50,
	0x14, 0x26, 0xdb, 0xba, 0xb6, 0xa7, 0xac, 0x6b, 0x6f, 0xed, 0xec, 0x62, 0xcb, 0x66, 0x54, 0x9c,
	0x43, 0x1b, 0x98, 0x4c, 0x50, 0xf0, 0xc5, 0x6d, 0xcc, 0x81, 0x4c, 0x89, 0x83, 0x81, 0x82, 0xe5,
	0xb6, 0xb9, 0x2b, 0xd7, 0xb6, 0x49, 0x96, 0xdc, 0x74, 0x9b, 0xe2, 0x8b, 0xf8, 0x22, 0xf8, 0xe6,
	0x1f, 0xf0, 0xff, 0xf8, 0xe8, 0x5f, 0xf0, 0x87, 0xc8, 0xbd, 0xb9, 0x49, 0x93, 0x36, 0xed, 0x26,
	0xec, 0xad, 0xf7, 0xdc, 0x73, 0xbf, 0xef, 0x7c, 0xdf, 0xc9, 0x39, 0x85, 0x92, 0xd3, 0xd6, 0x1d,
	0x7c, 0x31, 0x20, 0x16, 0x6b, 0x3a, 0xae, 0xcd, 0x6c, 0x94, 0x97, 0x47, 0xa7, 0xad, 0xd6, 0xbb,
	0xb6, 0xdd, 0xed, 0x13, 0x1d, 0x3b, 0x54, 0xc7, 0x96, 0x65, 0x33, 0xcc, 0xa8, 0x6d, 0x79, 0x41,
	0xa2, 0xba, 0x26, 0x6f, 0xc5, 0xa9, 0xed, 0x9f, 0xe8, 0x8c, 0x0e, 0x88, 0xc7, 0xf0, 0xc0, 0x09,
	0x12, 0x34, 0x02, 0xcb, 0x3b, 0xd8, 0x35, 0x0f, 0xac, 0x13, 0xdb, 0x1d, 0x88, 0xa7, 0x68, 0x0d,
	0x0a, 0x1d, 0xec, 0x9a, 0x2d, 0xcb, 0x1f, 0xb4, 0x89, 0x5b, 0x53, 0xd6, 0x95, 0x8d, 0xbc, 0x01,
	0x3c, 0x74, 0x28, 0x22, 0xa8, 0x04, 0xf3, 0x9d, 0xe1, 0xb0, 0x36, 0x27, 0x2e, 0xf8, 0x4f, 0xfe,
	0x84, 0x9c, 0x3b, 0xd4, 0xbd, 0x68, 0x99, 0x98, 0x91, 0xda, 0x7c, 0xf0, 0x24, 0x08, 0xed, 0x62,
	0x46, 0xb4, 0x77, 0x50, 0x36, 0x48, 0x97, 0x7a, 0x8c, 0x93, 0x19, 0xe4, 0xd4, 0x27, 0x1e, 0x43,
	0x7b, 0x50, 0x12, 0x44, 0x74, 0x44, 0x2e, 0xd8, 0x0a, 0x5b, 0x6a, 0x33, 0x12, 0xd8, 0x1c, 0x2b,
	0xcf, 0x58, 0xee, 0x24, 0x03, 0xda, 0x4b, 0x40, 0x71, 0x6c, 0xcf, 0xb1, 0x2d, 0x8f, 0xa0, 0x06,
	0x88, 0x92, 0x5b, 0xcc, 0xee, 0x11, 0x4b, 0x8a, 0xc8, 0xf3, 0xc8, 0x11, 0x0f, 0xa0, 0x0a, 0x64,
	0xa8, 0xd7, 0xb2, 0x7b, 0x42, 0x45, 0xce, 0x58, 0xa0, 0xde, 0xeb, 0x9e, 0xf6, 0x5b, 0x01, 0xf4,
	0x26, 0x20, 0x8e, 0x1b, 0x72, 0x09, 0xd4, 0x3d, 0x28, 0xba, 0xc4, 0x23, 0xee, 0x50, 0x64, 0xb7,
	0xa8, 0x29, 0x30, 0x33, 0xc6, 0x52, 0x2c, 0x7a, 0x60, 0xa2, 0x27, 0x90, 0xe3, 0xe6, 0xf0, 0x06,
	0x08, 0x83, 0xb8, 0xca, 0xa0, 0x3b, 0xcd, 0xb0, 0x3b, 0xcd, 0xa3, 0xb0, 0x3b, 0x46, 0x94, 0x8b,
	0x56, 0x60, 0x11, 0x0f, 0x6c, 0xdf, 0x62, 0xb5, 0x05, 0x01, 0x2b, 0x4f, 0xdc, 0x73, 0xea, 0xb5,
	0x3a, 0xd8, 0xea, 0x90, 0x3e, 0x31, 0x6b, 0x19, 0xa1, 0x03, 0xa8, 0xb7, 0x23, 0x23, 0x5a, 0x17,
	0xaa, 0x7b, 0xe7, 0xa4, 0xe3, 0x33, 0x22, 0x35, 0x85, 0xbe, 0x1f, 0x42, 0x45, 0xda, 0x9b, 0x62,
	0x7d, 0x23, 0x66, 0xfd, 0xa4, 0x17, 0x06, 0x72, 0x26, 0x62, 0xda, 0x2b, 0x58, 0x19, 0x27, 0x1a,
	0x35, 0x21, 0x62, 0x32, 0x43, 0xe7, 0x42, 0x04, 0x33, 0xbd, 0x09, 0xdb, 0x70, 0x23, 0x90, 0x30,
	0x56, 0xf5, 0x6c, 0x2c, 0xed, 0x21, 0x54, 0xc7, 0x9e, 0xc9, 0x1a, 0x22, 0x12, 0x25, 0x46, 0xf2,
	0x14, 0x6a, 0x2f, 0xfc, 0x7e, 0xef, 0x4a, 0x44, 0xf3, 0x49, 0xa2, 0x6d, 0x58, 0x4d, 0x79, 0x2a,
	0xc9, 0x6a, 0x90, 0x35, 0x49, 0x9f, 0x30, 0x12, 0x54, 0x98, 0x31, 0xc2, 0xa3, 0xf6, 0x1c, 0xea,
	0xfb, 0x84, 0xa5, 0x38, 0x7a, 0x35, 0x79, 0xdf, 0x14, 0x68, 0x4c, 0x79, 0x2f, 0xa9, 0xaf, 0xb9,
	0xab, 0xe9, 0xcd, 0xa9, 0x40, 0xf9, 0xc0, 0xa2, 0x8c, 0xe2, 0x3e, 0xfd, 0x44, 0x64, 0xe9, 0xda,
	0x03, 0x40, 0xf1, 0xe0, 0x2c, 0xdf, 0x11, 0x94, 0xf6, 0x09, 0xb7, 0xcb, 0xef, 0x87, 0x7e, 0x6b,
	0xbf, 0x14, 0xc8, 0x1a, 0xf8, 0x6c, 0x17, 0x33, 0x7c, 0xed, 0x22, 0xd2, 0x56, 0xcc, 0xdc, 0xff,
	0xaf, 0x98, 0x63, 0x28, 0xc7, 0xca, 0x96, 0x02, 0x1f, 0x41, 0xce, 0xc5, 0x67, 0x7c, 0xe3, 0x61,
	0xf1, 0x95, 0x14, 0xb6, 0x50, 0x0c, 0x53, 0x2a, 0x32, 0xb2, 0xae, 0x94, 0x96, 0xe6, 0xe7, 0xd6,
	0x8f, 0x45, 0x28, 0x4a, 0x29, 0x6f, 0x89, 0x3b, 0xa4, 0x1d, 0x82, 0xde, 0x03, 0x8c, 0xd6, 0x19,
	0xaa, 0xc7, 0x21, 0xc7, 0x37, 0xa8, 0xda, 0x98, 0x72, 0x1b, 0x54, 0xa8, 0x95, 0xbe, 0xfe, 0xf9,
	0xfb, 0x73, 0x0e, 0xb4, 0x8c, 0xce, 0x05, 0x3d, 0x53, 0x36, 0xd1, 0x47, 0x28, 0x26, 0x47, 0x15,
	0xad, 0xc7, 0x20, 0x52, 0xd7, 0x85, 0x7a, 0x7b, 0x46, 0x86, 0x24, 0xaa, 0x08, 0xa2, 0x25, 0x2d,
	0x17, 0xfe, 0x4f, 0x71, 0xae, 0x53, 0x58, 0x4a, 0x0c, 0x09, 0x5a, 0x4b, 0x58, 0x3e, 0x39, 0x79,
	0xea, 0xfa, 0xf4, 0x04, 0x49, 0xd4, 0x10, 0x44, 0x37, 0x37, 0xab, 0x21, 0x91, 0xfe, 0x79, 0x34,
	0x35, 0x5f, 0xd0, 0x05, 0x94, 0x27, 0x66, 0x13, 0xdd, 0x89, 0xa1, 0x4e, 0x1b, 0x7a, 0xf5, 0xee,
	0xec, 0x24, 0x49, 0xbf, 0x2a, 0xe8, 0x2b, 0x5a, 0x31, 0xa2, 0x6f, 0xb5, 0xfd, 0x7e, 0x8f, 0xab,
	0xfd, 0xae, 0x40, 0x35, 0x75, 0x40, 0xd1, 0xfd, 0x18, 0xf4, 0xac, 0x15, 0xa0, 0x6e, 0x5c, 0x9e,
	0x98, 0xb4, 0x01, 0x4d, 0xb1, 0xe1, 0x03, 0xc0, 0x68, 0x20, 0x13, 0x9f, 0xd0, 0xc4, 0xf0, 0x26,
	0x3e, 0xa1, 0xc9, 0x29, 0x8e, 0x3a, 0x5b, 0xd0, 0xe9, 0x08, 0xf1, 0x18, 0xf2, 0xd1, 0x38, 0xa0,
	0x5b, 0xc9, 0xaa, 0x13, 0xb3, 0xad, 0xd6, 0xd3, 0x2f, 0x25, 0xf8, 0xb2, 0x00, 0xcf, 0xa3, 0xac,
	0xee, 0x8a, 0x8b, 0xf6, 0xa2, 0xf8, 0x27, 0x7c, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xe9,
	0x76, 0xa4, 0xf2, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	//クレジットカードのトークン発行(非保持化対応)
	RegistCard(ctx context.Context, in *RegistCardRequest, opts ...grpc.CallOption) (*RegistCardResponse, error)
	//決済を行う
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error)
	//決済をバルクでキャンセルする
	BulkCancelPayment(ctx context.Context, in *BulkCancelPaymentRequest, opts ...grpc.CallOption) (*BulkCancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error)
	//メモリ初期化
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	//ベンチマーカー用結果取得API
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) RegistCard(ctx context.Context, in *RegistCardRequest, opts ...grpc.CallOption) (*RegistCardResponse, error) {
	out := new(RegistCardResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/RegistCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error) {
	out := new(ExecutePaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/ExecutePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error) {
	out := new(CancelPaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/CancelPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) BulkCancelPayment(ctx context.Context, in *BulkCancelPaymentRequest, opts ...grpc.CallOption) (*BulkCancelPaymentResponse, error) {
	out := new(BulkCancelPaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/BulkCancelPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error) {
	out := new(GetPaymentInformationResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/GetPaymentInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/Initialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/GetResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	//クレジットカードのトークン発行(非保持化対応)
	RegistCard(context.Context, *RegistCardRequest) (*RegistCardResponse, error)
	//決済を行う
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(context.Context, *CancelPaymentRequest) (*CancelPaymentResponse, error)
	//決済をバルクでキャンセルする
	BulkCancelPayment(context.Context, *BulkCancelPaymentRequest) (*BulkCancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(context.Context, *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error)
	//メモリ初期化
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	//ベンチマーカー用結果取得API
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) RegistCard(ctx context.Context, req *RegistCardRequest) (*RegistCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistCard not implemented")
}
func (*UnimplementedPaymentServiceServer) ExecutePayment(ctx context.Context, req *ExecutePaymentRequest) (*ExecutePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) CancelPayment(ctx context.Context, req *CancelPaymentRequest) (*CancelPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPayment not implemented")
}
func (*UnimplementedPaymentServiceServer) BulkCancelPayment(ctx context.Context, req *BulkCancelPaymentRequest) (*BulkCancelPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkCancelPayment not implemented")
}
func (*UnimplementedPaymentServiceServer) GetPaymentInformation(ctx context.Context, req *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentInformation not implemented")
}
func (*UnimplementedPaymentServiceServer) Initialize(ctx context.Context, req *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (*UnimplementedPaymentServiceServer) GetResult(ctx context.Context, req *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_RegistCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RegistCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/RegistCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RegistCard(ctx, req.(*RegistCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/ExecutePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/CancelPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_BulkCancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).BulkCancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/BulkCancelPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).BulkCancelPayment(ctx, req.(*BulkCancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/GetPaymentInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, req.(*GetPaymentInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/GetResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paymentpb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistCard",
			Handler:    _PaymentService_RegistCard_Handler,
		},
		{
			MethodName: "ExecutePayment",
			Handler:    _PaymentService_ExecutePayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _PaymentService_CancelPayment_Handler,
		},
		{
			MethodName: "BulkCancelPayment",
			Handler:    _PaymentService_BulkCancelPayment_Handler,
		},
		{
			MethodName: "GetPaymentInformation",
			Handler:    _PaymentService_GetPaymentInformation_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _PaymentService_Initialize_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _PaymentService_GetResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/payment.proto",
}
