// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package paymentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentInformation struct {
	CardNumber           string               `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Datetime             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Cvv                  string               `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Amount               int32                `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentInformation) Reset()         { *m = PaymentInformation{} }
func (m *PaymentInformation) String() string { return proto.CompactTextString(m) }
func (*PaymentInformation) ProtoMessage()    {}
func (*PaymentInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *PaymentInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInformation.Unmarshal(m, b)
}
func (m *PaymentInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInformation.Marshal(b, m, deterministic)
}
func (m *PaymentInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInformation.Merge(m, src)
}
func (m *PaymentInformation) XXX_Size() int {
	return xxx_messageInfo_PaymentInformation.Size(m)
}
func (m *PaymentInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInformation proto.InternalMessageInfo

func (m *PaymentInformation) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *PaymentInformation) GetDatetime() *timestamp.Timestamp {
	if m != nil {
		return m.Datetime
	}
	return nil
}

func (m *PaymentInformation) GetCvv() string {
	if m != nil {
		return m.Cvv
	}
	return ""
}

func (m *PaymentInformation) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ExecutePaymentRequest struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ExecutePaymentRequest) Reset()         { *m = ExecutePaymentRequest{} }
func (m *ExecutePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentRequest) ProtoMessage()    {}
func (*ExecutePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *ExecutePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentRequest.Unmarshal(m, b)
}
func (m *ExecutePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentRequest.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentRequest.Merge(m, src)
}
func (m *ExecutePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentRequest.Size(m)
}
func (m *ExecutePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentRequest proto.InternalMessageInfo

func (m *ExecutePaymentRequest) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

type ExecutePaymentResponse struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutePaymentResponse) Reset()         { *m = ExecutePaymentResponse{} }
func (m *ExecutePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentResponse) ProtoMessage()    {}
func (*ExecutePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *ExecutePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentResponse.Unmarshal(m, b)
}
func (m *ExecutePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentResponse.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentResponse.Merge(m, src)
}
func (m *ExecutePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentResponse.Size(m)
}
func (m *ExecutePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentResponse proto.InternalMessageInfo

func (m *ExecutePaymentResponse) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type CancelPaymentRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentRequest) Reset()         { *m = CancelPaymentRequest{} }
func (m *CancelPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentRequest) ProtoMessage()    {}
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *CancelPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentRequest.Unmarshal(m, b)
}
func (m *CancelPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentRequest.Marshal(b, m, deterministic)
}
func (m *CancelPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentRequest.Merge(m, src)
}
func (m *CancelPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentRequest.Size(m)
}
func (m *CancelPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentRequest proto.InternalMessageInfo

func (m *CancelPaymentRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type CancelPaymentResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentResponse) Reset()         { *m = CancelPaymentResponse{} }
func (m *CancelPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentResponse) ProtoMessage()    {}
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{4}
}

func (m *CancelPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentResponse.Unmarshal(m, b)
}
func (m *CancelPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentResponse.Marshal(b, m, deterministic)
}
func (m *CancelPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentResponse.Merge(m, src)
}
func (m *CancelPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentResponse.Size(m)
}
func (m *CancelPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentResponse proto.InternalMessageInfo

func (m *CancelPaymentResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type GetPaymentInformationRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentInformationRequest) Reset()         { *m = GetPaymentInformationRequest{} }
func (m *GetPaymentInformationRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationRequest) ProtoMessage()    {}
func (*GetPaymentInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{5}
}

func (m *GetPaymentInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationRequest.Unmarshal(m, b)
}
func (m *GetPaymentInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationRequest.Merge(m, src)
}
func (m *GetPaymentInformationRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationRequest.Size(m)
}
func (m *GetPaymentInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationRequest proto.InternalMessageInfo

func (m *GetPaymentInformationRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type GetPaymentInformationResponse struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPaymentInformationResponse) Reset()         { *m = GetPaymentInformationResponse{} }
func (m *GetPaymentInformationResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationResponse) ProtoMessage()    {}
func (*GetPaymentInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{6}
}

func (m *GetPaymentInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationResponse.Unmarshal(m, b)
}
func (m *GetPaymentInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationResponse.Merge(m, src)
}
func (m *GetPaymentInformationResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationResponse.Size(m)
}
func (m *GetPaymentInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationResponse proto.InternalMessageInfo

func (m *GetPaymentInformationResponse) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func init() {
	proto.RegisterType((*PaymentInformation)(nil), "paymentpb.PaymentInformation")
	proto.RegisterType((*ExecutePaymentRequest)(nil), "paymentpb.ExecutePaymentRequest")
	proto.RegisterType((*ExecutePaymentResponse)(nil), "paymentpb.ExecutePaymentResponse")
	proto.RegisterType((*CancelPaymentRequest)(nil), "paymentpb.CancelPaymentRequest")
	proto.RegisterType((*CancelPaymentResponse)(nil), "paymentpb.CancelPaymentResponse")
	proto.RegisterType((*GetPaymentInformationRequest)(nil), "paymentpb.GetPaymentInformationRequest")
	proto.RegisterType((*GetPaymentInformationResponse)(nil), "paymentpb.GetPaymentInformationResponse")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x8b, 0xd3, 0x50,
	0x14, 0x25, 0x9d, 0x0f, 0x3a, 0xb7, 0x74, 0x90, 0x5b, 0x33, 0x86, 0x30, 0xa1, 0x31, 0x1b, 0xc3,
	0x20, 0x09, 0x54, 0x54, 0x10, 0x5c, 0x89, 0xc8, 0x6c, 0x46, 0x89, 0xee, 0xcb, 0x4b, 0xf2, 0x5a,
	0x62, 0x9b, 0xf7, 0xd2, 0xe4, 0xa5, 0x28, 0xe2, 0xc6, 0x9d, 0x6b, 0x17, 0xfe, 0x30, 0xff, 0x82,
	0xff, 0xc2, 0x8d, 0xf4, 0xe5, 0xa5, 0x9f, 0x69, 0xeb, 0xc2, 0x5d, 0xee, 0xcd, 0xb9, 0xe7, 0x9c,
	0x7b, 0x2e, 0x0f, 0xba, 0x19, 0xf9, 0x9c, 0x52, 0x26, 0xbc, 0x2c, 0xe7, 0x82, 0xe3, 0x85, 0x2a,
	0xb3, 0xd0, 0xbc, 0x1e, 0x73, 0x3e, 0x9e, 0x52, 0x9f, 0x64, 0x89, 0x4f, 0x18, 0xe3, 0x82, 0x88,
	0x84, 0xb3, 0xa2, 0x02, 0x9a, 0x7d, 0xf5, 0x57, 0x56, 0x61, 0x39, 0xf2, 0x45, 0x92, 0xd2, 0x42,
	0x90, 0x34, 0xab, 0x00, 0xce, 0x4f, 0x0d, 0xf0, 0x5d, 0x45, 0x76, 0xcb, 0x46, 0x3c, 0x4f, 0xe5,
	0x38, 0xf6, 0xa1, 0x13, 0x91, 0x3c, 0x1e, 0xb2, 0x32, 0x0d, 0x69, 0x6e, 0x68, 0xb6, 0xe6, 0x5e,
	0x04, 0xb0, 0x68, 0xdd, 0xc9, 0x0e, 0x3e, 0x83, 0x76, 0x4c, 0x04, 0x5d, 0xd0, 0x19, 0x2d, 0x5b,
	0x73, 0x3b, 0x03, 0xd3, 0xab, 0xb4, 0xbc, 0x5a, 0xcb, 0xfb, 0x50, 0x6b, 0x05, 0x4b, 0x2c, 0xde,
	0x83, 0x93, 0x68, 0x3e, 0x37, 0x4e, 0x24, 0xe1, 0xe2, 0x13, 0xaf, 0xe0, 0x9c, 0xa4, 0xbc, 0x64,
	0xc2, 0x38, 0xb5, 0x35, 0xf7, 0x2c, 0x50, 0x95, 0x33, 0x06, 0xfd, 0xf5, 0x27, 0x1a, 0x95, 0x82,
	0x2a, 0x7f, 0x01, 0x9d, 0x95, 0xb4, 0x10, 0x78, 0x07, 0x3d, 0xb5, 0xfe, 0x30, 0x59, 0x59, 0x96,
	0x1e, 0x3b, 0x03, 0xcb, 0x5b, 0x46, 0xe3, 0xed, 0xee, 0x15, 0x60, 0xb6, 0xd3, 0x73, 0x9e, 0xc3,
	0xd5, 0xb6, 0x50, 0x91, 0x71, 0x56, 0x50, 0xb4, 0x00, 0x96, 0x4a, 0xb1, 0x0a, 0xa1, 0x8e, 0xfe,
	0x36, 0x76, 0x9e, 0xc2, 0xfd, 0x57, 0x84, 0x45, 0x74, 0xba, 0x65, 0xf0, 0xc8, 0xd8, 0x63, 0xd0,
	0xb7, 0xc6, 0x94, 0x5c, 0x0f, 0xce, 0x92, 0x62, 0xc8, 0x27, 0x72, 0xa4, 0x1d, 0x9c, 0x26, 0xc5,
	0xdb, 0x89, 0xf3, 0x12, 0xae, 0xdf, 0x50, 0xd1, 0xb0, 0xca, 0xbf, 0x89, 0x71, 0xb0, 0xf6, 0x8c,
	0x2b, 0xd1, 0xff, 0x9c, 0xe6, 0xe0, 0x4f, 0x0b, 0x2e, 0x15, 0xf4, 0x3d, 0xcd, 0xe7, 0x49, 0x44,
	0xf1, 0x23, 0x5c, 0x6e, 0x06, 0x8c, 0xf6, 0x1a, 0x6f, 0xe3, 0x91, 0xcd, 0x87, 0x07, 0x10, 0x95,
	0x73, 0xa7, 0xf7, 0xed, 0xd7, 0xef, 0x1f, 0xad, 0xae, 0xd3, 0xf6, 0x15, 0xf4, 0x85, 0x76, 0x83,
	0x33, 0xe8, 0x6e, 0x84, 0x8b, 0xfd, 0x35, 0xa2, 0xa6, 0x6b, 0x99, 0xf6, 0x7e, 0x80, 0x12, 0xb2,
	0xa4, 0xd0, 0x83, 0x1b, 0xbd, 0x16, 0xf2, 0xbf, 0xac, 0x22, 0xff, 0x8a, 0xdf, 0x35, 0xd0, 0x1b,
	0x33, 0xc6, 0x47, 0x6b, 0xd4, 0x87, 0x8e, 0x68, 0xba, 0xc7, 0x81, 0x9b, 0x5e, 0xb0, 0xd9, 0x4b,
	0x78, 0x2e, 0x1f, 0xdf, 0x93, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x96, 0xd8, 0x7b, 0x30,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	//決済を行う
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error) {
	out := new(ExecutePaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/ExecutePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error) {
	out := new(CancelPaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/CancelPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error) {
	out := new(GetPaymentInformationResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/GetPaymentInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	//決済を行う
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(context.Context, *CancelPaymentRequest) (*CancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(context.Context, *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) ExecutePayment(ctx context.Context, req *ExecutePaymentRequest) (*ExecutePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) CancelPayment(ctx context.Context, req *CancelPaymentRequest) (*CancelPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPayment not implemented")
}
func (*UnimplementedPaymentServiceServer) GetPaymentInformation(ctx context.Context, req *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentInformation not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/ExecutePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/CancelPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/GetPaymentInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, req.(*GetPaymentInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paymentpb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePayment",
			Handler:    _PaymentService_ExecutePayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _PaymentService_CancelPayment_Handler,
		},
		{
			MethodName: "GetPaymentInformation",
			Handler:    _PaymentService_GetPaymentInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
