// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package paymentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardInformation struct {
	CardNumber           string   `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Cvv                  string   `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardInformation) Reset()         { *m = CardInformation{} }
func (m *CardInformation) String() string { return proto.CompactTextString(m) }
func (*CardInformation) ProtoMessage()    {}
func (*CardInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *CardInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardInformation.Unmarshal(m, b)
}
func (m *CardInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardInformation.Marshal(b, m, deterministic)
}
func (m *CardInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardInformation.Merge(m, src)
}
func (m *CardInformation) XXX_Size() int {
	return xxx_messageInfo_CardInformation.Size(m)
}
func (m *CardInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_CardInformation.DiscardUnknown(m)
}

var xxx_messageInfo_CardInformation proto.InternalMessageInfo

func (m *CardInformation) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *CardInformation) GetCvv() string {
	if m != nil {
		return m.Cvv
	}
	return ""
}

func (m *CardInformation) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

type RegistCardRequest struct {
	CardInformtion       *CardInformation `protobuf:"bytes,1,opt,name=card_informtion,json=cardInformtion,proto3" json:"card_informtion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegistCardRequest) Reset()         { *m = RegistCardRequest{} }
func (m *RegistCardRequest) String() string { return proto.CompactTextString(m) }
func (*RegistCardRequest) ProtoMessage()    {}
func (*RegistCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *RegistCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistCardRequest.Unmarshal(m, b)
}
func (m *RegistCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistCardRequest.Marshal(b, m, deterministic)
}
func (m *RegistCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistCardRequest.Merge(m, src)
}
func (m *RegistCardRequest) XXX_Size() int {
	return xxx_messageInfo_RegistCardRequest.Size(m)
}
func (m *RegistCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistCardRequest proto.InternalMessageInfo

func (m *RegistCardRequest) GetCardInformtion() *CardInformation {
	if m != nil {
		return m.CardInformtion
	}
	return nil
}

type RegistCardResponse struct {
	CardToken            string   `protobuf:"bytes,1,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	IsOk                 bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistCardResponse) Reset()         { *m = RegistCardResponse{} }
func (m *RegistCardResponse) String() string { return proto.CompactTextString(m) }
func (*RegistCardResponse) ProtoMessage()    {}
func (*RegistCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *RegistCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistCardResponse.Unmarshal(m, b)
}
func (m *RegistCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistCardResponse.Marshal(b, m, deterministic)
}
func (m *RegistCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistCardResponse.Merge(m, src)
}
func (m *RegistCardResponse) XXX_Size() int {
	return xxx_messageInfo_RegistCardResponse.Size(m)
}
func (m *RegistCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistCardResponse proto.InternalMessageInfo

func (m *RegistCardResponse) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *RegistCardResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type PaymentInformation struct {
	CardToken            string   `protobuf:"bytes,1,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IsCanceled           bool     `protobuf:"varint,5,opt,name=is_canceled,json=isCanceled,proto3" json:"is_canceled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentInformation) Reset()         { *m = PaymentInformation{} }
func (m *PaymentInformation) String() string { return proto.CompactTextString(m) }
func (*PaymentInformation) ProtoMessage()    {}
func (*PaymentInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *PaymentInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInformation.Unmarshal(m, b)
}
func (m *PaymentInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInformation.Marshal(b, m, deterministic)
}
func (m *PaymentInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInformation.Merge(m, src)
}
func (m *PaymentInformation) XXX_Size() int {
	return xxx_messageInfo_PaymentInformation.Size(m)
}
func (m *PaymentInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInformation proto.InternalMessageInfo

func (m *PaymentInformation) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *PaymentInformation) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentInformation) GetIsCanceled() bool {
	if m != nil {
		return m.IsCanceled
	}
	return false
}

type ExecutePaymentRequest struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ExecutePaymentRequest) Reset()         { *m = ExecutePaymentRequest{} }
func (m *ExecutePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentRequest) ProtoMessage()    {}
func (*ExecutePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{4}
}

func (m *ExecutePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentRequest.Unmarshal(m, b)
}
func (m *ExecutePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentRequest.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentRequest.Merge(m, src)
}
func (m *ExecutePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentRequest.Size(m)
}
func (m *ExecutePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentRequest proto.InternalMessageInfo

func (m *ExecutePaymentRequest) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

type ExecutePaymentResponse struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	IsOk                 bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutePaymentResponse) Reset()         { *m = ExecutePaymentResponse{} }
func (m *ExecutePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*ExecutePaymentResponse) ProtoMessage()    {}
func (*ExecutePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{5}
}

func (m *ExecutePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePaymentResponse.Unmarshal(m, b)
}
func (m *ExecutePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePaymentResponse.Marshal(b, m, deterministic)
}
func (m *ExecutePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePaymentResponse.Merge(m, src)
}
func (m *ExecutePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_ExecutePaymentResponse.Size(m)
}
func (m *ExecutePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePaymentResponse proto.InternalMessageInfo

func (m *ExecutePaymentResponse) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *ExecutePaymentResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type CancelPaymentRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentRequest) Reset()         { *m = CancelPaymentRequest{} }
func (m *CancelPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentRequest) ProtoMessage()    {}
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{6}
}

func (m *CancelPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentRequest.Unmarshal(m, b)
}
func (m *CancelPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentRequest.Marshal(b, m, deterministic)
}
func (m *CancelPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentRequest.Merge(m, src)
}
func (m *CancelPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentRequest.Size(m)
}
func (m *CancelPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentRequest proto.InternalMessageInfo

func (m *CancelPaymentRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type CancelPaymentResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPaymentResponse) Reset()         { *m = CancelPaymentResponse{} }
func (m *CancelPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CancelPaymentResponse) ProtoMessage()    {}
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{7}
}

func (m *CancelPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPaymentResponse.Unmarshal(m, b)
}
func (m *CancelPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPaymentResponse.Marshal(b, m, deterministic)
}
func (m *CancelPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPaymentResponse.Merge(m, src)
}
func (m *CancelPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CancelPaymentResponse.Size(m)
}
func (m *CancelPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPaymentResponse proto.InternalMessageInfo

func (m *CancelPaymentResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type GetPaymentInformationRequest struct {
	PaymentId            string   `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentInformationRequest) Reset()         { *m = GetPaymentInformationRequest{} }
func (m *GetPaymentInformationRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationRequest) ProtoMessage()    {}
func (*GetPaymentInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{8}
}

func (m *GetPaymentInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationRequest.Unmarshal(m, b)
}
func (m *GetPaymentInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationRequest.Merge(m, src)
}
func (m *GetPaymentInformationRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationRequest.Size(m)
}
func (m *GetPaymentInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationRequest proto.InternalMessageInfo

func (m *GetPaymentInformationRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

type GetPaymentInformationResponse struct {
	PaymentInformation   *PaymentInformation `protobuf:"bytes,1,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	IsOk                 bool                `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPaymentInformationResponse) Reset()         { *m = GetPaymentInformationResponse{} }
func (m *GetPaymentInformationResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentInformationResponse) ProtoMessage()    {}
func (*GetPaymentInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{9}
}

func (m *GetPaymentInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentInformationResponse.Unmarshal(m, b)
}
func (m *GetPaymentInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentInformationResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentInformationResponse.Merge(m, src)
}
func (m *GetPaymentInformationResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentInformationResponse.Size(m)
}
func (m *GetPaymentInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentInformationResponse proto.InternalMessageInfo

func (m *GetPaymentInformationResponse) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func (m *GetPaymentInformationResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func init() {
	proto.RegisterType((*CardInformation)(nil), "paymentpb.CardInformation")
	proto.RegisterType((*RegistCardRequest)(nil), "paymentpb.RegistCardRequest")
	proto.RegisterType((*RegistCardResponse)(nil), "paymentpb.RegistCardResponse")
	proto.RegisterType((*PaymentInformation)(nil), "paymentpb.PaymentInformation")
	proto.RegisterType((*ExecutePaymentRequest)(nil), "paymentpb.ExecutePaymentRequest")
	proto.RegisterType((*ExecutePaymentResponse)(nil), "paymentpb.ExecutePaymentResponse")
	proto.RegisterType((*CancelPaymentRequest)(nil), "paymentpb.CancelPaymentRequest")
	proto.RegisterType((*CancelPaymentResponse)(nil), "paymentpb.CancelPaymentResponse")
	proto.RegisterType((*GetPaymentInformationRequest)(nil), "paymentpb.GetPaymentInformationRequest")
	proto.RegisterType((*GetPaymentInformationResponse)(nil), "paymentpb.GetPaymentInformationResponse")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0x12, 0x41,
	0x14, 0xc7, 0xb3, 0xa5, 0x34, 0xe5, 0x35, 0xd0, 0x3a, 0x48, 0x25, 0x1b, 0x08, 0xb8, 0x17, 0x49,
	0x63, 0xd8, 0xa4, 0xc6, 0x8b, 0x89, 0x27, 0x34, 0x6a, 0x62, 0xaa, 0x59, 0x3d, 0x98, 0x78, 0x20,
	0xc3, 0xee, 0x2b, 0x19, 0x61, 0x77, 0xb6, 0x3b, 0xb3, 0xa4, 0x8d, 0xf1, 0x62, 0xbc, 0x78, 0xf6,
	0xa3, 0x79, 0xf1, 0x03, 0xf8, 0x41, 0xcc, 0xcc, 0x0e, 0xb0, 0xc0, 0x42, 0x3d, 0xf4, 0xc6, 0xbc,
	0x79, 0xef, 0xfd, 0xde, 0xff, 0x3f, 0x6f, 0x81, 0x6a, 0x4c, 0x6f, 0x42, 0x8c, 0x64, 0x3f, 0x4e,
	0xb8, 0xe4, 0xa4, 0x62, 0x8e, 0xf1, 0xc8, 0x6e, 0x8d, 0x39, 0x1f, 0x4f, 0xd1, 0xa5, 0x31, 0x73,
	0x69, 0x14, 0x71, 0x49, 0x25, 0xe3, 0x91, 0xc8, 0x12, 0xed, 0x8e, 0xb9, 0xd5, 0xa7, 0x51, 0x7a,
	0xe9, 0x4a, 0x16, 0xa2, 0x90, 0x34, 0x8c, 0xb3, 0x04, 0x07, 0xe1, 0x78, 0x40, 0x93, 0xe0, 0x4d,
	0x74, 0xc9, 0x93, 0x50, 0x97, 0x92, 0x0e, 0x1c, 0xf9, 0x34, 0x09, 0x86, 0x51, 0x1a, 0x8e, 0x30,
	0x69, 0x5a, 0x5d, 0xab, 0x57, 0xf1, 0x40, 0x85, 0x2e, 0x74, 0x84, 0x9c, 0x40, 0xc9, 0x9f, 0xcd,
	0x9a, 0x7b, 0xfa, 0x42, 0xfd, 0x54, 0x25, 0x78, 0x1d, 0xb3, 0xe4, 0x66, 0x18, 0x50, 0x89, 0xcd,
	0x52, 0x56, 0x92, 0x85, 0x5e, 0x50, 0x89, 0xce, 0x27, 0xb8, 0xe7, 0xe1, 0x98, 0x09, 0xa9, 0x60,
	0x1e, 0x5e, 0xa5, 0x28, 0x24, 0x19, 0xc0, 0xb1, 0x06, 0x31, 0x0d, 0x57, 0x6c, 0x0d, 0x3b, 0x3a,
	0xb7, 0xfb, 0x0b, 0x7d, 0xfd, 0xb5, 0xe9, 0xbc, 0x9a, 0xbf, 0x08, 0xa8, 0xb3, 0xf3, 0x1a, 0x48,
	0xbe, 0xb3, 0x88, 0x79, 0x24, 0x90, 0xb4, 0x41, 0x0f, 0x3c, 0x94, 0x7c, 0x82, 0x91, 0x91, 0x50,
	0x51, 0x91, 0x8f, 0x2a, 0x40, 0xea, 0x50, 0x66, 0x62, 0xc8, 0x27, 0x5a, 0xc3, 0xa1, 0xb7, 0xcf,
	0xc4, 0xbb, 0x89, 0x33, 0x05, 0xf2, 0x3e, 0xc3, 0xe6, 0xdd, 0xb8, 0xa5, 0xd3, 0x29, 0x1c, 0xd0,
	0x90, 0xa7, 0x91, 0x6c, 0xee, 0x77, 0xad, 0x5e, 0xd9, 0x33, 0x27, 0xe5, 0x08, 0x13, 0x43, 0x9f,
	0x46, 0x3e, 0x4e, 0x31, 0x68, 0x96, 0x35, 0x07, 0x98, 0x18, 0x98, 0x88, 0x33, 0x86, 0xc6, 0xcb,
	0x6b, 0xf4, 0x53, 0x89, 0x06, 0x3a, 0x77, 0xe5, 0x02, 0xea, 0x46, 0xbd, 0x31, 0x86, 0xe6, 0x9c,
	0x69, 0xe7, 0x9c, 0xd9, 0x1c, 0xd6, 0x23, 0xf1, 0x46, 0xcc, 0x79, 0x0b, 0xa7, 0xeb, 0xa0, 0xa5,
	0x49, 0x0b, 0x52, 0x30, 0x97, 0x36, 0xef, 0x10, 0x14, 0x9b, 0xf4, 0x14, 0xee, 0x67, 0x12, 0xd6,
	0xa6, 0xde, 0xdd, 0xcb, 0x79, 0x0c, 0x8d, 0xb5, 0x32, 0x33, 0xc3, 0x02, 0x62, 0xe5, 0x20, 0xcf,
	0xa1, 0xf5, 0x0a, 0x65, 0x81, 0xbe, 0xff, 0x83, 0xfd, 0xb0, 0xa0, 0xbd, 0xa5, 0xde, 0x50, 0xef,
	0xd8, 0xe3, 0x42, 0xab, 0xce, 0xff, 0x94, 0xa0, 0x66, 0xea, 0x3f, 0x60, 0x32, 0x63, 0x3e, 0x92,
	0xcf, 0x00, 0xcb, 0x65, 0x25, 0xad, 0x1c, 0x68, 0xe3, 0xeb, 0xb0, 0xdb, 0x5b, 0x6e, 0x33, 0x09,
	0xce, 0xc9, 0xf7, 0xdf, 0x7f, 0x7f, 0xed, 0x81, 0x53, 0x76, 0xd5, 0x32, 0x3e, 0xb3, 0xce, 0xc8,
	0x17, 0xa8, 0xad, 0x3e, 0x34, 0xe9, 0xe6, 0x5a, 0x14, 0x2e, 0x9b, 0xfd, 0x70, 0x47, 0x86, 0x01,
	0xd5, 0x35, 0xa8, 0xea, 0x1c, 0xba, 0x26, 0x55, 0xb1, 0xae, 0xa0, 0xba, 0xf2, 0x9e, 0xa4, 0xb3,
	0xf2, 0xc9, 0x6e, 0x2e, 0x88, 0xdd, 0xdd, 0x9e, 0x60, 0x40, 0x6d, 0x0d, 0x7a, 0x70, 0xd6, 0x98,
	0x83, 0xdc, 0xaf, 0xcb, 0x57, 0xfe, 0x46, 0x7e, 0x5a, 0xd0, 0x28, 0x7c, 0x55, 0xf2, 0x28, 0xd7,
	0x7a, 0xd7, 0xde, 0xd8, 0xbd, 0xdb, 0x13, 0x57, 0x67, 0x21, 0xc5, 0xb3, 0x8c, 0x0e, 0xf4, 0x9f,
	0xe7, 0x93, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0x10, 0xba, 0x23, 0x97, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	//クレジットカードのトークン発行(非保持化対応)
	RegistCard(ctx context.Context, in *RegistCardRequest, opts ...grpc.CallOption) (*RegistCardResponse, error)
	//決済を行う
	ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) RegistCard(ctx context.Context, in *RegistCardRequest, opts ...grpc.CallOption) (*RegistCardResponse, error) {
	out := new(RegistCardResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/RegistCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ExecutePayment(ctx context.Context, in *ExecutePaymentRequest, opts ...grpc.CallOption) (*ExecutePaymentResponse, error) {
	out := new(ExecutePaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/ExecutePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error) {
	out := new(CancelPaymentResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/CancelPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentInformation(ctx context.Context, in *GetPaymentInformationRequest, opts ...grpc.CallOption) (*GetPaymentInformationResponse, error) {
	out := new(GetPaymentInformationResponse)
	err := c.cc.Invoke(ctx, "/paymentpb.PaymentService/GetPaymentInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	//クレジットカードのトークン発行(非保持化対応)
	RegistCard(context.Context, *RegistCardRequest) (*RegistCardResponse, error)
	//決済を行う
	ExecutePayment(context.Context, *ExecutePaymentRequest) (*ExecutePaymentResponse, error)
	//決済をキャンセルする
	CancelPayment(context.Context, *CancelPaymentRequest) (*CancelPaymentResponse, error)
	//決済情報を取得する
	GetPaymentInformation(context.Context, *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) RegistCard(ctx context.Context, req *RegistCardRequest) (*RegistCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistCard not implemented")
}
func (*UnimplementedPaymentServiceServer) ExecutePayment(ctx context.Context, req *ExecutePaymentRequest) (*ExecutePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) CancelPayment(ctx context.Context, req *CancelPaymentRequest) (*CancelPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPayment not implemented")
}
func (*UnimplementedPaymentServiceServer) GetPaymentInformation(ctx context.Context, req *GetPaymentInformationRequest) (*GetPaymentInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentInformation not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_RegistCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RegistCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/RegistCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RegistCard(ctx, req.(*RegistCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/ExecutePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ExecutePayment(ctx, req.(*ExecutePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/CancelPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.PaymentService/GetPaymentInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentInformation(ctx, req.(*GetPaymentInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paymentpb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistCard",
			Handler:    _PaymentService_RegistCard_Handler,
		},
		{
			MethodName: "ExecutePayment",
			Handler:    _PaymentService_ExecutePayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _PaymentService_CancelPayment_Handler,
		},
		{
			MethodName: "GetPaymentInformation",
			Handler:    _PaymentService_GetPaymentInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
