INSERT INTO distance_fare_master(distance, fare) VALUES (0, 2500);
INSERT INTO distance_fare_master(distance, fare) VALUES (50, 3000);
INSERT INTO distance_fare_master(distance, fare) VALUES (75, 3700);
INSERT INTO distance_fare_master(distance, fare) VALUES (100, 4500);
INSERT INTO distance_fare_master(distance, fare) VALUES (150, 5200);
INSERT INTO distance_fare_master(distance, fare) VALUES (200, 6000);
INSERT INTO distance_fare_master(distance, fare) VALUES (300, 7200);
INSERT INTO distance_fare_master(distance, fare) VALUES (400, 8300);
INSERT INTO distance_fare_master(distance, fare) VALUES (500, 12000);
INSERT INTO distance_fare_master(distance, fare) VALUES (1000, 20000);

INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('東京',0.000000,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('古岡',12.745608,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('絵寒町',32.107649,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('沙芦公園',45.037138,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('形顔',52.773422,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('油交',60.930427,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('通墨山',72.915666,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('初野',80.517696,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('樺威学園',96.053004,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('塩鮫公園',112.665386,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('奥山',119.444708,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('表岡',131.462232,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('並取',149.826976,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('細野',166.909255,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('住郷',182.323457,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('管英',188.887999,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('気川',207.599747,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('桐飛',217.900353,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('樫曲町',229.697609,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('依酒山',244.770170,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('堀切町',251.948590,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('葉千',269.009280,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('奥山',275.384825,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('鯉秋寺',284.952294,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('伍出',291.499545,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('杏高公園',310.086023,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('竹利台',325.553902,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('磯川',334.561908,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('茶川',343.842013,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('八実学園',355.192588,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('梓金',374.584703,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('鯉田',381.847874,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('鳴門',393.244289,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('曲徳町',411.802367,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('彩岬山',420.375925,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('根永',428.829478,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('鹿近川',445.676144,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('結広',457.246917,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('庵金公園',474.044387,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('近岡',487.270404,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('威香',504.163580,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('名古屋',519.612391,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('錦太学園',531.408202,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('和錦台',548.584849,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('稲冬台',554.215596,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('松港山',572.885503,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('甘桜',584.344724,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('根左海岸',603.713433,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('島威寺',614.711098,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('月朱野',633.406177,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('芋呉川',640.097895,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('木南',657.573946,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('鳩平ヶ丘',677.211495,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('維荻学園',689.581633,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('保池',696.405431,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('九野',711.087956,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('桜田',728.268005,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('霞苑野',735.983348,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('夷太寺',744.581560,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('甘野',751.340202,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('遠山',770.125141,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('銀正',788.163214,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('末国',799.939778,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('泉別川',807.476895,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('京都',819.772794,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('桜内',833.349255,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('荻葛ヶ丘',839.298450,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('雨墨',853.080719,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('桂綾寺',863.842723,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('笠霞海岸',869.266132,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('塚手海岸',878.247393,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('垣通海岸',893.724394,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('雨稲ヶ丘',900.098745,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('森果川',909.518544,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('舟田',919.249073,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('形利',938.540025,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('午万台',954.151248,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('早森野',966.498192,0,0,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('桐氷野',975.568259,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('条川',990.339004,1,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('菊岡',1005.597665,0,1,1);
INSERT INTO station_master(name,distance,is_stop_express,is_stop_semi_express,is_stop_local) VALUES('大阪',1024.983484,1,1,1);