package scenario

import (
	"time"

	"github.com/chibiegg/isucon9-final/bench/isutrain"
)

var pretestSearchTrainsTests = []struct {
	useAt                time.Time
	from                 string
	to                   string
	trainClass           string
	adult, child         int
	wantSeatAvailability map[string]map[string]string
	wantFareInformation  map[string]map[string]int
	wantDepartedAt       map[string]string
	wantArrivedAt        map[string]string
}{
	{
		useAt:      time.Date(2020, 1, 1, 10, 0, 0, 0, time.UTC),
		from:       "東京",
		to:         "大阪",
		trainClass: "最速",
		adult:      1,
		child:      1,
		wantSeatAvailability: map[string]map[string]string{

			"49": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"51": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"53": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"63": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"71": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"83": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"87": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"93": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"97": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"101": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},
		},
		wantFareInformation: map[string]map[string]int{

			"49": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"51": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"53": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"63": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"71": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"83": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"87": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"93": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"97": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"101": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},
		},
		wantDepartedAt: map[string]string{
			"49":  "10:08:00",
			"51":  "10:18:00",
			"53":  "10:27:00",
			"63":  "11:18:00",
			"71":  "12:01:00",
			"83":  "13:03:00",
			"87":  "13:23:00",
			"93":  "13:53:00",
			"97":  "14:15:00",
			"101": "14:35:00",
		},
		wantArrivedAt: map[string]string{
			"49":  "12:17:59",
			"51":  "12:27:59",
			"53":  "12:36:59",
			"63":  "13:27:59",
			"71":  "14:10:59",
			"83":  "15:12:59",
			"87":  "15:32:59",
			"93":  "16:02:59",
			"97":  "16:24:59",
			"101": "16:44:59",
		},
	},
	{
		useAt:      time.Date(2020, 1, 1, 12, 0, 0, 0, time.UTC),
		from:       "大阪",
		to:         "東京",
		trainClass: "最速",
		adult:      1,
		child:      1,
		wantSeatAvailability: map[string]map[string]string{

			"52": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"54": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"56": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"62": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"64": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"66": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"82": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"88": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"92": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},

			"130": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "○",
			},
		},
		wantFareInformation: map[string]map[string]int{

			"52": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"54": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"56": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"62": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"64": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"66": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"82": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"88": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"92": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},

			"130": map[string]int{
				"non_reserved":   225000,
				"premium":        450000,
				"premium_smoke":  450000,
				"reserved":       281250,
				"reserved_smoke": 281250,
			},
		},
		wantDepartedAt: map[string]string{
			"52":  "12:24:59",
			"54":  "12:36:59",
			"56":  "12:47:59",
			"62":  "13:12:59",
			"64":  "13:21:59",
			"66":  "13:29:59",
			"82":  "14:54:59",
			"88":  "15:26:59",
			"92":  "15:49:59",
			"130": "19:09:59",
		},
		wantArrivedAt: map[string]string{
			"52":  "10:13:00",
			"54":  "10:25:00",
			"56":  "10:36:00",
			"62":  "11:01:00",
			"64":  "11:10:00",
			"66":  "11:18:00",
			"82":  "12:43:00",
			"88":  "13:15:00",
			"92":  "13:38:00",
			"130": "16:58:00",
		},
	},
	{
		useAt:      time.Date(2020, 1, 1, 14, 0, 0, 0, time.UTC),
		from:       "葉千",
		to:         "奥山",
		trainClass: "遅いやつ",
		adult:      1,
		child:      1,
		wantSeatAvailability: map[string]map[string]string{

			"77": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"81": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"85": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"89": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"91": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"95": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"103": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"105": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"109": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"117": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},
		},
		wantFareInformation: map[string]map[string]int{

			"77": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"81": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"85": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"89": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"91": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"95": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"103": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"105": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"109": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},

			"117": map[string]int{
				"non_reserved":   15000,
				"premium":        30000,
				"premium_smoke":  30000,
				"reserved":       18750,
				"reserved_smoke": 18750,
			},
		},
		wantDepartedAt: map[string]string{
			"77":  "14:10:42",
			"81":  "14:37:48",
			"85":  "14:51:59",
			"89":  "15:08:18",
			"91":  "15:19:19",
			"95":  "15:44:17",
			"103": "16:24:55",
			"105": "16:34:49",
			"109": "16:55:03",
			"117": "17:35:58",
		},
		wantArrivedAt: map[string]string{
			"77":  "14:11:30",
			"81":  "14:38:35",
			"85":  "14:52:47",
			"89":  "15:09:06",
			"91":  "15:20:06",
			"95":  "15:45:05",
			"103": "16:25:43",
			"105": "16:35:37",
			"109": "16:55:50",
			"117": "17:36:46",
		},
	},
	{
		useAt:      time.Date(2020, 1, 1, 14, 0, 0, 0, time.UTC),
		from:       "鳴門",
		to:         "東京",
		trainClass: "遅いやつ",
		adult:      2,
		child:      4,
		wantSeatAvailability: map[string]map[string]string{

			"72": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"76": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"78": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"98": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"100": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"102": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"104": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"112": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"120": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"124": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},
		},
		wantFareInformation: map[string]map[string]int{

			"72": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"76": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"78": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"98": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"100": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"102": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"104": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"112": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"120": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},

			"124": map[string]int{
				"non_reserved":   115200,
				"premium":        230400,
				"premium_smoke":  230400,
				"reserved":       144000,
				"reserved_smoke": 144000,
			},
		},
		wantDepartedAt: map[string]string{
			"72":  "14:17:31",
			"76":  "14:35:39",
			"78":  "14:48:17",
			"98":  "16:40:47",
			"100": "16:43:56",
			"102": "16:55:54",
			"104": "17:08:28",
			"112": "17:48:32",
			"120": "18:26:59",
			"124": "18:53:58",
		},
		wantArrivedAt: map[string]string{
			"72":  "11:47:00",
			"76":  "12:08:00",
			"78":  "12:20:00",
			"98":  "14:09:00",
			"100": "14:19:00",
			"102": "14:29:00",
			"104": "14:37:00",
			"112": "15:21:00",
			"120": "16:03:00",
			"124": "16:24:00",
		},
	},
	{
		useAt:      time.Date(2020, 1, 1, 13, 0, 0, 0, time.UTC),
		from:       "維荻学園",
		to:         "桐氷野",
		trainClass: "遅いやつ",
		adult:      2,
		child:      3,
		wantSeatAvailability: map[string]map[string]string{

			"35": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"37": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"57": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"65": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"67": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"77": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"81": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"85": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"89": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},

			"91": map[string]string{
				"non_reserved":   "○",
				"premium":        "○",
				"premium_smoke":  "×",
				"reserved":       "○",
				"reserved_smoke": "×",
			},
		},
		wantFareInformation: map[string]map[string]int{

			"35": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"37": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"57": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"65": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"67": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"77": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"81": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"85": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"89": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},

			"91": map[string]int{
				"non_reserved":   84000,
				"premium":        168000,
				"premium_smoke":  168000,
				"reserved":       105000,
				"reserved_smoke": 105000,
			},
		},
		wantDepartedAt: map[string]string{
			"35": "13:09:06",
			"37": "13:15:41",
			"57": "14:53:03",
			"65": "15:33:44",
			"67": "15:47:08",
			"77": "16:42:11",
			"81": "17:05:49",
			"85": "17:16:43",
			"89": "17:29:39",
			"91": "17:49:59",
		},
		wantArrivedAt: map[string]string{
			"35": "14:55:43",
			"37": "15:02:43",
			"57": "16:41:10",
			"65": "17:22:19",
			"67": "17:35:41",
			"77": "18:25:28",
			"81": "18:58:31",
			"85": "19:06:09",
			"89": "19:17:11",
			"91": "19:38:19",
		},
	},
}

var pretestSearchTrainSeatsTests = []struct {
	date               time.Time
	trainClass         string
	trainName          string
	carNum             int
	departure, arrival string
	wantSeats          isutrain.TrainSeats
	wantCars           isutrain.TrainCars
}{
	{
		date:       time.Date(2020, 1, 1, 12, 0, 0, 0, time.UTC),
		trainClass: "最速",
		trainName:  "71",
		carNum:     5,
		departure:  "東京",
		arrival:    "大阪",
		wantSeats: isutrain.TrainSeats{
			&isutrain.TrainSeat{Row: 1, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "A", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "B", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "C", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "D", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "E", Class: "reserved", IsSmokingSeat: true, IsOccupied: false},
		},
		wantCars: isutrain.TrainCars{
			&isutrain.TrainCar{CarNumber: 1, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 2, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 3, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 4, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 5, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 6, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 7, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 8, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 9, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 10, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 11, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 12, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 13, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 14, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 15, SeatClass: "reserved"},
			&isutrain.TrainCar{CarNumber: 16, SeatClass: "reserved"},
		},
	},
	{
		date:       time.Date(2020, 1, 1, 13, 0, 0, 0, time.UTC),
		trainClass: "遅いやつ",
		trainName:  "14",
		carNum:     4,
		departure:  "大阪",
		arrival:    "東京",
		wantSeats: isutrain.TrainSeats{
			&isutrain.TrainSeat{Row: 1, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 14, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 15, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 16, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 17, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 17, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 17, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 17, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 17, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 18, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 18, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 18, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 18, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 18, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 19, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 19, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 19, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 19, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 19, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 20, Column: "A", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 20, Column: "B", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 20, Column: "C", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 20, Column: "D", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 20, Column: "E", Class: "non-reserved", IsSmokingSeat: false, IsOccupied: false},
		},
		wantCars: isutrain.TrainCars{
			&isutrain.TrainCar{CarNumber: 1, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 2, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 3, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 4, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 5, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 6, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 7, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 8, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 9, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 10, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 11, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 12, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 13, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 14, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 15, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 16, SeatClass: "reserved"},
		},
	},
	{
		date:       time.Date(2020, 1, 1, 13, 0, 0, 0, time.UTC),
		trainClass: "遅いやつ",
		trainName:  "26",
		carNum:     16,
		departure:  "雨稲ヶ丘",
		arrival:    "油交",
		wantSeats: isutrain.TrainSeats{
			&isutrain.TrainSeat{Row: 1, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
		},
		wantCars: isutrain.TrainCars{
			&isutrain.TrainCar{CarNumber: 1, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 2, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 3, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 4, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 5, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 6, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 7, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 8, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 9, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 10, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 11, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 12, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 13, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 14, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 15, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 16, SeatClass: "reserved"},
		},
	},
	{
		date:       time.Date(2020, 1, 1, 13, 0, 0, 0, time.UTC),
		trainClass: "遅いやつ",
		trainName:  "50",
		carNum:     16,
		departure:  "名古屋",
		arrival:    "形顔",
		wantSeats: isutrain.TrainSeats{
			&isutrain.TrainSeat{Row: 1, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
		},
		wantCars: isutrain.TrainCars{
			&isutrain.TrainCar{CarNumber: 1, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 2, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 3, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 4, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 5, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 6, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 7, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 8, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 9, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 10, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 11, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 12, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 13, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 14, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 15, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 16, SeatClass: "reserved"},
		},
	},
	{
		date:       time.Date(2020, 1, 1, 13, 0, 0, 0, time.UTC),
		trainClass: "遅いやつ",
		trainName:  "77",
		carNum:     16,
		departure:  "桐飛",
		arrival:    "条川",
		wantSeats: isutrain.TrainSeats{
			&isutrain.TrainSeat{Row: 1, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 1, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 2, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 3, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 4, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 5, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 6, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 7, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 8, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 9, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 10, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 11, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 12, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "A", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "B", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "C", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "D", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
			&isutrain.TrainSeat{Row: 13, Column: "E", Class: "reserved", IsSmokingSeat: false, IsOccupied: false},
		},
		wantCars: isutrain.TrainCars{
			&isutrain.TrainCar{CarNumber: 1, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 2, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 3, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 4, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 5, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 6, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 7, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 8, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 9, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 10, SeatClass: "premium"},
			&isutrain.TrainCar{CarNumber: 11, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 12, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 13, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 14, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 15, SeatClass: "non-reserved"},
			&isutrain.TrainCar{CarNumber: 16, SeatClass: "reserved"},
		},
	},
}
